"""empty message

Revision ID: a2e2b3e8a040
Revises: cbb0c15bf827
Create Date: 2021-03-04 16:30:13.910295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e2b3e8a040'
down_revision = 'cbb0c15bf827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('editordata', sa.Text(), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.TEXT(), nullable=True))
    op.drop_column('post', 'editordata')
    # ### end Alembic commands ###
