"""empty message

Revision ID: cbb0c15bf827
Revises: 920f16cd54a4
Create Date: 2021-03-04 15:22:44.264152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb0c15bf827'
down_revision = '920f16cd54a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('color', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'color')
    # ### end Alembic commands ###
